language: ruby
dist: xenial
cache: bundler
rvm:
  - 2.6
script:
  - RAILS_ENV=test bundle exec rake --trace bootstrap spec
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
