language: ruby
cache: bundler
rvm:
  - 2.2.2
  - 2.1.6
  - 2.0.0
  - 1.9.3
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: 2.0.0
  fast_finish: true
script:
  - RAILS_ENV=test bundle exec rake --trace bootstrap spec
sudo: false